lanes.c: drop unused err_msg variable
Fixes this compilation failure (Wall/Werror combination catalyzes this):

	make[1]: Entering directory '/home/snoonan/Development/lua-lanes/src'
	gcc -Wall -Werror -O2 -I/usr/include/lua5.1  -D_GNU_SOURCE -fPIC   -c -o lanes.o lanes.c
	lanes.c: In function ‘run_finalizers’:
	lanes.c:1133:16: error: unused variable ‘err_msg’ [-Werror=unused-variable]
	    char const* err_msg = lua_tostring( L, error_index);
	                ^
	cc1: all warnings being treated as errors
	<builtin>: recipe for target 'lanes.o' failed
	make[1]: *** [lanes.o] Error 1

Signed-off-by: Steven Noonan <steven@uplinklabs.net>